"""STL(binary)/OBJ 내보내기 — 외부 의존성 없음."""
from __future__ import annotations

import io
import struct

import numpy as np


def to_stl(verts: np.ndarray, faces: np.ndarray, name: bytes = b"cowork") -> bytes:
    tri = verts[faces].astype(np.float32)  # (F,3,3)
    n = np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0])
    norm = np.linalg.norm(n, axis=1, keepdims=True)
    norm[norm < 1e-12] = 1.0
    n = (n / norm).astype(np.float32)

    buf = io.BytesIO()
    header = name[:80].ljust(80, b"\0")
    buf.write(header)
    buf.write(struct.pack("<I", len(faces)))
    data = np.empty((len(faces), 50), dtype=np.uint8)
    f32 = np.concatenate(
        [n.reshape(-1, 3), tri.reshape(-1, 9)], axis=1
    ).astype("<f4")  # (F,12)
    data[:, :48] = f32.view(np.uint8).reshape(len(faces), 48)
    data[:, 48:] = 0
    buf.write(data.tobytes())
    return buf.getvalue()


def to_obj(verts: np.ndarray, faces: np.ndarray) -> bytes:
    lines = [
        "# generated by Koft / FootFit AI",
        "# Copyright (c) 2026 Futuremine97 (Koft). All rights reserved.",
        "# Proprietary output. No redistribution or derivative use without written permission.",
    ]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    for f in faces:
        lines.append(f"f {f[0]+1} {f[1]+1} {f[2]+1}")
    return "\n".join(lines).encode("utf-8")


def points_to_ply(pts: np.ndarray) -> bytes:
    header = (
        "ply\nformat ascii 1.0\n"
        "comment generated by Koft / FootFit AI\n"
        "comment Copyright (c) 2026 Futuremine97 (Koft). All rights reserved.\n"
        "comment Proprietary output. No redistribution or derivative use without written permission.\n"
        f"element vertex {len(pts)}\n"
        "property float x\nproperty float y\nproperty float z\n"
        "end_header\n"
    )
    body = "\n".join(f"{p[0]:.6f} {p[1]:.6f} {p[2]:.6f}" for p in pts)
    return (header + body).encode("utf-8")
